language: node_js

# https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth
git:
  depth: 10

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - graphicsmagick
      - libcairo2-dev

before_install:

  # https://github.com/npm/npm/issues/11283
  - npm set progress=false

  - export SAVAGE_BRANCH="^savage-"

  - chmod +x ./scripts/browserstack-cleanup.sh
  - chmod +x ./scripts/npm-publish.sh
  - chmod +x ./scripts/releases-publish.sh
  - chmod +x ./scripts/visual-baseline.sh
  - chmod +x ./scripts/visual-failures.sh

# Run `ci` instead of default of `test`
script: npm run ci && ./scripts/visual-baseline.sh

# Upload coverage to https://codecov.io/gh/blackbaud/skyux2
after_script:
  - bash <(curl -s https://codecov.io/bash)
  - ./scripts/browserstack-cleanup.sh

# Publish a tag to NPM & skyux2-releases repo
after_success:
  - if [ -n "$TRAVIS_TAG" ]; then npm run releases; fi
  - if [ -n "$TRAVIS_TAG" ]; then ./scripts/npm-publish.sh; fi
  - if [ -n "$TRAVIS_TAG" ]; then ./scripts/releases-publish.sh; fi

# Display any NPM / BrowserStack errorsc
after_failure:
  - ./scripts/visual-baseline.sh
  - if [ -e ./npm-debug.log ]; then cat ./npm-debug.log; fi
  - if [ -e ./browserstack.err ]; then cat ./browserstack.err; fi

# When a push, only care about the master, rc-, and savage- branches.
# Otherwise anytime we commit to internal branches this would run.
branches:
  only:
    - master
    - /^rc-.*$/
    - /^savage-.*$/
    - /^[0-9]+\.[0-9]+\.[0-9]+.*/

# Cache a few things
cache:
  directories:
    - node_modules
    - $BROWSER_STACK_BINARY_BASE_PATH

notifications:
  slack:
    secure: X3VK9q9hmAcdzxdf8Ba0OHNThYoKKxvFLaDE09s45/75NM38pWQ9iOBJ8GOxYOA0WePzRNEScPxUAFMVKXK0KDbgtcEZ5DdM7kBe7JMo+fB39VLD3L70MVRLdpXnsPZE283GyXmjrmSVg+5gJrSYLwifnvyoqnnRlexL/Hz2JvxbDxdigbgLv8nvgEm5k62RN6kTVFS8aWI7sY1K1aEQdn8yTMy0u1VhBNA3wcFYVpAD1rbyBoSuFhARDVBujTh/RQamngDFLDThKGdCIvf57ierCgLFv6XLFPsviQP5qBMzEbBwu9u0DmOeevUsXUGUPtBSzQN9hBlMU995/n79PoSrlGGmBjISzqwzvp4JNMSDfCh+ne/PX1kIqeFW8egSTVTfCgavbHN4kJvtJZNmi6eDHhFHagSHSBkRgAc6JGvVHVToA1I/u97rcV1nVInhEvUNE6NZ/gkMj0El841ce3IvSZUsFcz/8IoYANxY1LCTmgnF/9GZ3QkKvBU0qhOjsMNnH2zwih38H1Ppqb0/+e+6mlmHpksnKgYwwAS83ZuKzyZbw7I3wyKUEOBCy7wWq45ZjRc74hnrZn/TngHyQ5UXCIlUBn1SjqjyljIKsp85A0lsZLcIEUIsR+7brnMRtMUW5IUaOSow2b52lr4suHG/ShXnUAe1sj2+uxCiy64=

# Save the browserstack binary to a known location so we can cache it
env:
  global:
    - CXX=g++-4.8
    - BROWSER_STACK_BINARY_BASE_PATH=$HOME/browserstack-binary
